### ISSUE TITLE
The output PowerPoint cannot always be opened without closing the script that produced it first

### ISSUE THREAD

**Issue by adecler** [BHoM/PowerPoint_Toolkit#3]
#### Description:
There must be cases where the output file is not released properly.. to be investigated. 

See comment from @FraserGreenroyd for discussion: https://github.com/BHoM/PowerPoint_Toolkit/pull/2#pullrequestreview-1335921111

**Comment by Tom-Kingstone** [comment]
The issue is caused by the `PresentationDocument.SaveAs()` method. This method creates a clone of the presentation document, and returns it as an output. Because this output isn't captured in a variable and closed afterwards, the created document remains open as a file stream, thus locking the document for use while the script is still open.

Not sure why the garbage collector doesn't close the stream when the adapter action completes though :/

In any case, simply ending the lines that handle saving documents with `.Close()` or `.Dispose()` will solve the issue
