### ISSUE TITLE
DocumentFormat_OpenXML not compliant with PowerPoint_Toolkit

### ISSUE THREAD

**Issue by JohannaOlin1** [BHoM/PowerPoint_Toolkit#8]
#### Description:
DocumentFormat_OpenXML is using an older version of System.IO.Packaging (2016) compared to Powerpoint_Toolkit (2019) which causes issues when the newer System.IO.Packaging.dll is installed with the daily alpha.

**Comment by FraserGreenroyd** [comment]
I've transferred this from Excel Toolkit to PowerPoint toolkit because A) fixing it on Excel became quite a headache and B) downgrading it on PowerPoint didn't cause any detrimental effect that I could find.

Given PowerPoint is currently in alpha, vs Excel in beta, and the pressing project needs to get this resolved to allow alpha testing on SAP Toolkit (fyi @rboulton-BH ), I am going for downgrading this, with a desire to then align both to a higher version in the future.

**Comment by FraserGreenroyd** [comment]
Actually I was wrong, I hadn't hit the right button on my end 🤦‍♂️ so will need to investigate further and determine a solution. Might transfer back to Excel after all.
